"""도감(코덱스) 오버뷰 컴포저.

일괄 생성된 여러 개체의 대표 이미지 + 이름/역할/핵심 지표를 하나의
도감 페이지 이미지로 조합한다.
"""
from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw

from ..models import EntityConcept
from . import asset_catalog as cat
from .fonts import load_font

BG = (16, 14, 24)
CARD = (30, 27, 45)
INK = (232, 228, 240)
SUB = (168, 162, 190)

_TITLE = {"character": "캐릭터 도감", "monster": "몬스터 도감", "npc": "NPC 명부"}
# 개체 카드에 강조 표시할 지표 (엔티티별)
_HILIGHT_STAT = {"monster": ("위협도", "저항"), "character": ("공격력", "체력"),
                 "npc": ("친밀도", "신뢰도")}


def _hex(h: str):
    h = h.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    try:
        return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))
    except ValueError:
        return (200, 155, 60)


def _accent(concept: EntityConcept):
    p = concept.color_palette
    return _hex(p[2] if len(p) > 2 else (p[0] if p else "#C89B3C"))


def compose_codex(
    entity_type: str,
    entries: list[tuple[EntityConcept, Path | None]],
    out_png: Path,
) -> Path:
    """entries: (concept, portrait_path) 목록 → 도감 이미지."""
    cols = 2 if len(entries) <= 4 else 3
    rows = (len(entries) + cols - 1) // cols

    pad = 40
    gap = 26
    card_w = 380
    card_h = 200
    header_h = 120

    W = pad * 2 + card_w * cols + gap * (cols - 1)
    H = header_h + pad + rows * card_h + gap * (rows - 1) + pad

    img = Image.new("RGB", (W, H), BG)
    draw = ImageDraw.Draw(img, "RGBA")

    # 헤더
    accent = _accent(entries[0][0]) if entries else (200, 155, 60)
    draw.rectangle([0, 0, W, header_h], fill=CARD)
    draw.rectangle([0, header_h, W, header_h + 5], fill=accent)
    title = _TITLE.get(entity_type, "도감")
    draw.text((pad, 30), title, font=load_font(48, bold=True), fill=INK)
    draw.text((pad, 88), f"총 {len(entries)}개체 · Generated by AXData Studio",
              font=load_font(20), fill=SUB)

    hi = _HILIGHT_STAT.get(entity_type, ("공격력", "체력"))

    for idx, (concept, portrait) in enumerate(entries):
        r, c = divmod(idx, cols)
        x = pad + c * (card_w + gap)
        y = header_h + pad + r * (card_h + gap)
        _draw_entry(img, draw, concept, portrait, x, y, card_w, card_h, hi)

    out_png.parent.mkdir(parents=True, exist_ok=True)
    img.save(out_png, "PNG")
    return out_png


def _draw_entry(img, draw, concept, portrait, x, y, w, h, hi_names) -> None:
    accent = _accent(concept)
    draw.rounded_rectangle([x, y, x + w, y + h], radius=14, fill=CARD)

    # 좌측 대표 이미지
    thumb = h - 24
    if portrait and Path(portrait).exists():
        p = Image.open(portrait).convert("RGB").resize((thumb, thumb), Image.LANCZOS)
        mask = Image.new("L", (thumb, thumb), 0)
        ImageDraw.Draw(mask).rounded_rectangle([0, 0, thumb, thumb], radius=10, fill=255)
        img.paste(p, (x + 12, y + 12), mask)
    else:
        draw.rounded_rectangle([x + 12, y + 12, x + 12 + thumb, y + 12 + thumb],
                               radius=10, fill=(50, 46, 70))

    # 우측 텍스트
    tx = x + 12 + thumb + 16
    tw = x + w - tx - 14
    draw.text((tx, y + 18), (concept.name or "?")[:12], font=load_font(28, bold=True), fill=INK)
    role_line = " · ".join(z for z in [concept.role, concept.genre] if z)[:22]
    draw.text((tx, y + 54), role_line, font=load_font(18), fill=accent)

    # 태그라인 2줄
    ty = y + 84
    tag = concept.tagline or concept.title
    for line in _wrap(draw, tag, load_font(16), tw)[:2]:
        draw.text((tx, ty), line, font=load_font(16), fill=SUB)
        ty += 22

    # 핵심 지표 2개 (미니 바)
    by = y + h - 46
    stat_map = {s.name: s.value for s in concept.stats}
    for name in hi_names:
        val = stat_map.get(name)
        if val is None:
            continue
        draw.text((tx, by - 2), name, font=load_font(15, bold=True), fill=SUB)
        bx = tx + 70
        bw = tw - 70
        draw.rounded_rectangle([bx, by + 2, bx + bw, by + 12], radius=5, fill=(50, 46, 70))
        fw = int(bw * val / 100)
        if fw > 8:
            draw.rounded_rectangle([bx, by + 2, bx + fw, by + 12], radius=5, fill=accent)
        by += 22


def _wrap(draw, text, font, max_w) -> list[str]:
    if not text:
        return []
    lines, cur = [], ""
    for ch in text:
        if draw.textlength(cur + ch, font=font) <= max_w:
            cur += ch
        else:
            lines.append(cur)
            cur = ch
    lines.append(cur)
    return lines
